version: 2
jobs:
  development:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      LAYER_PRERELEASE_REPO_URL: https://raw.githubusercontent.com/layerhq/releases-android/prerelease/releases/
    steps:
      - checkout
      - run:
          name: Checkout submodule
          command: git submodule sync && git submodule update --init
      - run:
          name: Create google-services.json
          command: eval "$DUMMY_GOOGLE_SERVICES_JSON_CONFIG"
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
  release:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Checkout submodule
          command: git submodule sync && git submodule update --init
      - run:
          name: Create google-services.json
          command: eval "$DUMMY_GOOGLE_SERVICES_JSON_CONFIG"
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

workflows:
  version: 2
  development:
    jobs:
      - development:
          filters:
            branches:
              ignore: master
  release:
    jobs:
      - release:
          filters:
            branches:
              only: master